# MCU
MCU = atmega328p
# Clock frequency
F_CPU = 16000000UL

# Compiler flags
CFLAGS = -mmcu=$(MCU) -DF_CPU=$(F_CPU) -Os

# Programmer/board settings
PROGRAMMER = arduino
PORT = /dev/tty.usbmodem11101
BAUD = 115200

#make sure to change the TARGET name for future projects
TARGET = helloDFR
#source file
SRC = $(TARGET).c

# tool chain
CC = avr-gcc #compiler
OBJCOPY = avr-objcopy # hex file generator
AVRDUDE = avrdude # this one flases the hex file into the microcontroller

all: $(TARGET).hex

$(TARGET).elf: $(SRC)
	$(CC) $(CFLAGS) -o $@ $<

$(TARGET).hex: $(TARGET).elf
	$(OBJCOPY) -O ihex -R .eeprom $< $@

flash: $(TARGET).hex
	$(AVRDUDE) -F -V -c $(PROGRAMMER) -p $(MCU) -P $(PORT) -b $(BAUD) -U flash:w:$<

clean:
	rm -f *.elf *.hex
