# MCU and clock
MCU = atmega328p
F_CPU = 16000000UL

# Compiler flags
CFLAGS = -mmcu=$(MCU) -DF_CPU=$(F_CPU) -Os

# Programmer/board settings
PROGRAMMER = arduino
PORT = /dev/tty.usbmodem11101
BAUD = 115200

# Files
TARGET = helloDFR
SRC = $(TARGET).c

# Tools
CC = avr-gcc
OBJCOPY = avr-objcopy
AVRDUDE = avrdude

all: $(TARGET).hex

$(TARGET).elf: $(SRC)
	$(CC) $(CFLAGS) -o $@ $<

$(TARGET).hex: $(TARGET).elf
	$(OBJCOPY) -O ihex -R .eeprom $< $@

flash: $(TARGET).hex
	$(AVRDUDE) -F -V -c $(PROGRAMMER) -p $(MCU) -P $(PORT) -b $(BAUD) -U flash:w:$<

clean:
	rm -f *.elf *.hex
